In [3]:
import numpy as np

**Question 1**

In [4]:
arr = np.arange(2,50,3)
arr

array([ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47])

**Question 2**

In [15]:
arr1 = np.array([int(x) for x in input().split()])
arr2 = np.array([int(x) for x in input().split()])

1 345 7 8 9
5 9 2 8 1


In [16]:
concat_arr = np.concatenate((arr1,arr2),axis=0)
print(concat_arr)

[  1 345   7   8   9   5   9   2   8   1]


In [17]:
concat_arr.sort()
print(concat_arr)

[  1   1   2   5   7   8   8   9   9 345]


**Question 3**

In [18]:
arr3 = np.array([[1,24,54],[8,4,9],[24,9,4]])
print('Dimensions: ',arr3.ndim )
print('Size: ',arr3.size )

Dimensions:  2
Size:  9


**Question 4**

In [32]:
arr4 = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15])
print(np.expand_dims(arr4,1))

# We can also use resize
print('Before resize: ',arr4) # before resize
arr4.resize((5,3)) 
print('After resize: ',arr4) #After resize

[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]
 [15]]
Before resize:  [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
After resize:  [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]


**Question 5**

In [44]:
arr5 = np.array([[ 1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
arr6 = np.array([[5,6,7,8],[13,14,15,16],[9,10,11,12],[ 1,2,3,4]])
print('Stacked Vertically: ' ,np.vstack((arr5,arr6)))
print('Stacked Horizontally: ' ,np.hstack((arr5,arr6)))

Stacked Vertically:  [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [ 5  6  7  8]
 [13 14 15 16]
 [ 9 10 11 12]
 [ 1  2  3  4]]
Stacked Horizontally:  [[ 1  2  3  4  5  6  7  8]
 [ 5  6  7  8 13 14 15 16]
 [ 9 10 11 12  9 10 11 12]
 [13 14 15 16  1  2  3  4]]


**Question 6**

In [52]:
print(arr3)
uniq_tuple = np.unique(arr3,return_counts=True)
print('Unique items in the array are: ',uniq_tuple[0])
print('Unique items Counts are: ',uniq_tuple[1])

[[ 1 24 54]
 [ 8  4  9]
 [24  9  4]]
Unique items in the array are:  [ 1  4  8  9 24 54]
Unique items Counts are:  [1 2 1 2 2 1]
